### ISSUE TITLE
Remove AB3-related Classes

### ISSUE THREAD

**Issue by yongkheehou** [AY2425S1-CS2103T-T16-2/tp#76]
Remove AB3-related classes in the code and remove the AB3 features in the User Guide 

## Todos
- [ ] Remove all unused Command Classes (e.g. `AddCommand`) and their Parsers
- [ ] Remove command from the parsing
- [ ] Update `ModelManager` and `LogicManager` to remove AB3-specific components
- [ ] Remove UI Components and controllers specific to AB3 features
